import { Text, View } from "react-native";
import { money } from "../formatters";

type Props = { hasCurrentBudget: boolean; debtBudgetMinor: number; requiredTotalMinor: number; surplusMinor: number; shortfallMinor: number; forecastMonths: number | null; forecastDate?: string | null; creditCardTargetMinor?: number; missingCardStrategyCount?: number; strategyRequired?: boolean; overview?: { totalPaidMinor: number; totalOriginalMinor: number; totalRemainingMinor: number; monthlyPayments: Array<{ month: string; amountMinor: number }> } };

export function DebtPlanSummary({ hasCurrentBudget, debtBudgetMinor, requiredTotalMinor, surplusMinor, shortfallMinor, forecastMonths, forecastDate, creditCardTargetMinor = 0, missingCardStrategyCount = 0, strategyRequired = false, overview }: Props) {
  return <>
    {!hasCurrentBudget ? <View style={{ backgroundColor: "#FFF4D6", borderRadius: 12, padding: 12 }}><Text style={{ color: "#6B4E00", fontWeight: "700" }}>Set up a current monthly budget to plan debt payments.</Text><Text style={{ color: "#6B4E00", fontSize: 12, marginTop: 4 }}>Available debt budget is currently {money(0)}.</Text></View> : null}
    <View style={{ backgroundColor: "#F1F0EB", borderRadius: 16, padding: 14, gap: 6 }}><Text style={{ fontWeight: "700", color: "#1B1C1A" }}>Plan this cycle</Text><Text>Debt budget: {money(debtBudgetMinor)}</Text><Text>Required payments: {money(requiredTotalMinor + creditCardTargetMinor)}</Text><Text>Surplus: {money(surplusMinor)} · Shortfall: {money(shortfallMinor)}</Text>{overview ? <><Text>Total paid: {money(overview.totalPaidMinor)}</Text><Text>Progress: {overview.totalOriginalMinor ? `${Math.round(((overview.totalOriginalMinor - overview.totalRemainingMinor) / overview.totalOriginalMinor) * 100)}%` : "0%"}</Text><Text>Payment trend: {overview.monthlyPayments.length ? overview.monthlyPayments.slice(0, 3).map((item) => `${item.month} ${money(item.amountMinor)}`).join(" · ") : "No payment history"}</Text></> : null}{strategyRequired ? <Text style={{ color: "#8A4B00", fontSize: 12 }}>A repayment strategy is required for every active credit-card statement before planning.</Text> : null}<Text style={{ color: "#6B7A6F", fontSize: 12 }}>Estimated debt-free date: {forecastDate ?? (forecastMonths === null ? "not available" : `${forecastMonths} month${forecastMonths === 1 ? "" : "s"}`)}</Text>{creditCardTargetMinor > 0 ? <Text style={{ color: "#414942", fontSize: 12 }}>Credit-card targets: {money(creditCardTargetMinor)} (reserved before Snowball/Avalanche ordering)</Text> : null}</View>
  </>;
}
