import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, TextInput, View } from "react-native";
import { createFinancialAccount, listFinancialAccounts, type FinancialAccount } from "../../local-db/repositories/financialFoundations";
import {
  applyCreditCardBalance, createCreditCardCycle, createCreditCardInstallment, deleteCreditCard, getCreditCard,
  listCreditCardCycleTransactions, listCreditCardCycles, listCreditCardInstallments, listCreditCardPayments,
  listCreditCardSettlements, listCreditCards, recordCreditCardPayment, recordCreditCardStatement,
  recognizeCreditCardPayment, recognizeCreditCardSettlement, requestCreditCardSettlement, saveCreditCard,
  setCreditCardStatementStrategy, type CreditCard, type CreditCardCycle, type CreditCardCycleTransaction,
  type CreditCardInstallment, type CreditCardPayment, type CreditCardSettlement,
} from "../../local-db/repositories/creditCards";
import { CREDIT_CARD_MESSAGES } from "./creditCardLogic";

type Props = { userId: string; deviceId: string; cardId?: string; onBack?: () => void; onOpenCard?: (id: string) => void; onSyncRequested?: () => Promise<void> };
const inputStyle = { borderWidth: 1, borderColor: "#EAEAE6", borderRadius: 12, padding: 12, backgroundColor: "#F7EED9" } as const;
const buttonStyle = { padding: 12, borderRadius: 12, backgroundColor: "#013220" } as const;
const money = (value: number | null) => value == null ? "Not recorded" : `PHP ${(value / 100).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);

export default function CreditCardsScreen({ userId, deviceId, cardId, onBack, onOpenCard, onSyncRequested }: Props) {
  const [cards, setCards] = useState<CreditCard[]>([]); const [card, setCard] = useState<CreditCard | null>(null);
  const [cycles, setCycles] = useState<CreditCardCycle[]>([]); const [selectedCycleId, setSelectedCycleId] = useState<string | null>(null);
  const [installments, setInstallments] = useState<CreditCardInstallment[]>([]); const [payments, setPayments] = useState<CreditCardPayment[]>([]);
  const [transactions, setTransactions] = useState<CreditCardCycleTransaction[]>([]); const [settlements, setSettlements] = useState<CreditCardSettlement[]>([]);
  const [accounts, setAccounts] = useState<FinancialAccount[]>([]); const [sourceAccounts, setSourceAccounts] = useState<FinancialAccount[]>([]);
  const [accountId, setAccountId] = useState(""); const [cardName, setCardName] = useState(""); const [issuer, setIssuer] = useState(""); const [limit, setLimit] = useState(""); const [available, setAvailable] = useState(""); const [cutoff, setCutoff] = useState(""); const [statementDate, setStatementDate] = useState(""); const [cardNotes, setCardNotes] = useState("");
  const [cycleStart, setCycleStart] = useState(""); const [cycleCutoff, setCycleCutoff] = useState(""); const [cycleStatement, setCycleStatement] = useState(""); const [statementBalance, setStatementBalance] = useState(""); const [minimumDue, setMinimumDue] = useState(""); const [financeCharge, setFinanceCharge] = useState(""); const [dueDate, setDueDate] = useState("");
  const [paymentAmount, setPaymentAmount] = useState(""); const [paymentDate, setPaymentDate] = useState(today()); const [paymentSourceAccount, setPaymentSourceAccount] = useState(""); const [paymentSubcategory, setPaymentSubcategory] = useState(""); const [paymentNotes, setPaymentNotes] = useState(""); const [paymentId, setPaymentId] = useState(""); const [applicationTarget, setApplicationTarget] = useState(""); const [applicationAmount, setApplicationAmount] = useState(""); const [applicationDate, setApplicationDate] = useState(today()); const [strategy, setStrategy] = useState<"pay_full" | "pay_minimum" | "custom">("pay_full"); const [custom, setCustom] = useState(""); const [settlementId, setSettlementId] = useState(""); const [settlementDate, setSettlementDate] = useState(today()); const [settlementAmount, setSettlementAmount] = useState(""); const [settlementFee, setSettlementFee] = useState(""); const [settlementStatus, setSettlementStatus] = useState("requested");
  const [installmentDescription, setInstallmentDescription] = useState(""); const [installmentOriginal, setInstallmentOriginal] = useState(""); const [installmentRemaining, setInstallmentRemaining] = useState(""); const [installmentTerm, setInstallmentTerm] = useState(""); const [installmentMonths, setInstallmentMonths] = useState(""); const [installmentAmortization, setInstallmentAmortization] = useState(""); const [installmentRate, setInstallmentRate] = useState("0"); const [installmentInterestType] = useState<"zero_interest" | "interest_bearing">("zero_interest");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [confirmCardDelete, setConfirmCardDelete] = useState(false);
  const cents = (value: string) => Math.round(Number(value) * 100);
  async function load() { setLoading(true); setError(null); try { setCards(await listCreditCards(userId)); const allAccounts = await listFinancialAccounts(userId); setAccounts(allAccounts.filter((item) => item.kind === "credit_card" && item.status === "active")); setSourceAccounts(allAccounts.filter((item) => item.kind !== "credit_card" && item.status === "active")); const selected = cardId ? await getCreditCard(userId, cardId) : null; setCard(selected); if (selected) { const nextCycles = await listCreditCardCycles(userId, selected.accountId); setCycles(nextCycles); const nextCycleId = selectedCycleId && nextCycles.some((cycle) => cycle.id === selectedCycleId) ? selectedCycleId : null; setSelectedCycleId(nextCycleId); setInstallments(await listCreditCardInstallments(userId, selected.accountId)); setSettlements(await listCreditCardSettlements(userId, selected.accountId)); if (nextCycleId) { const [nextPayments, nextTransactions] = await Promise.all([listCreditCardPayments(userId, nextCycleId), listCreditCardCycleTransactions(userId, nextCycleId)]); setPayments(nextPayments); setTransactions(nextTransactions); } else { setPayments([]); setTransactions([]); } } } catch { setError(CREDIT_CARD_MESSAGES.error); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [userId, cardId]);
  useEffect(() => { const selected = cycles.find((item) => item.id === selectedCycleId); if (!selected?.strategy) return; setStrategy(selected.strategy); setCustom(selected.strategy === "custom" && selected.customAmountMinor != null ? String(selected.customAmountMinor / 100) : ""); }, [cycles, selectedCycleId]);
  useEffect(() => { if (!selectedCycleId) { setPayments([]); setTransactions([]); return; } void Promise.all([listCreditCardPayments(userId, selectedCycleId), listCreditCardCycleTransactions(userId, selectedCycleId)]).then(([nextPayments, nextTransactions]) => { setPayments(nextPayments); setTransactions(nextTransactions); }).catch(() => setError(CREDIT_CARD_MESSAGES.error)); }, [userId, selectedCycleId]);
  async function run(work: () => Promise<unknown>, message: string) { setSaving(true); setError(null); setSuccess(null); try { await work(); setSuccess(message); await load(); await onSyncRequested?.(); } catch (value) { setError(value instanceof Error ? value.message : CREDIT_CARD_MESSAGES.error); } finally { setSaving(false); } }
  const field = (value: string, setValue: (value: string) => void, placeholder: string) => placeholder === "Source account (optional)" ? <View><Text>Select payment source account</Text>{sourceAccounts.length > 0 ? sourceAccounts.map((item) => <Pressable key={item.id} accessibilityLabel={`Select payment source ${item.id}`} onPress={() => setValue(item.id)}><Text>{value === item.id ? "● " : "○ "}{item.name}</Text></Pressable>) : <Text>No eligible active non-card accounts are available.</Text>}</View> : <TextInput value={value} onChangeText={setValue} placeholder={placeholder} style={inputStyle} />;
  const selector = (value: string, setValue: (value: string) => void, label: string, options: { id: string; label: string }[]) => <View><Text>{label}</Text>{options.length > 0 ? options.map((item) => <Pressable key={item.id} accessibilityLabel={`${label} ${item.id}`} onPress={() => setValue(item.id)}><Text>{value === item.id ? "● " : "○ "}{item.label}</Text></Pressable>) : <Text>No eligible records are available.</Text>}</View>;
  const action = (label: string, work: () => Promise<unknown>, message: string) => <Pressable accessibilityLabel={label} disabled={saving} onPress={() => void run(work, message)} style={buttonStyle}><Text style={{ color: "#fff", textAlign: "center", fontWeight: "800" }}>{saving ? "Saving..." : label}</Text></Pressable>;
  if (loading) return <View><Text>{CREDIT_CARD_MESSAGES.loading}</Text><ActivityIndicator color="#0E6D46" /></View>;
  if (!cardId) return <View style={{ gap: 14 }}><Text style={{ fontSize: 24, fontWeight: "800" }}>Credit cards</Text>{error && <Text>{error}</Text>}{cards.length === 0 ? <Text>{CREDIT_CARD_MESSAGES.empty}</Text> : cards.map((item) => <Pressable key={item.accountId} onPress={() => onOpenCard?.(item.accountId)}><Text>{item.issuer || "Credit card"}</Text><Text>Limit {money(item.creditLimitMinor)} · Available {money(item.availableCreditMinor)}</Text></Pressable>)}{accounts.length > 0 ? <View><Text>Select an existing credit-card account</Text>{accounts.map((item) => <Pressable key={item.id} onPress={() => { setAccountId(item.id); setCardName(item.name); }}><Text>{accountId === item.id ? "● " : "○ "}{item.name}</Text></Pressable>)}</View> : null}{field(cardName, setCardName, "Enter card name")}{field(issuer, setIssuer, "Enter bank or card issuer")}{field(limit, setLimit, "Enter credit limit")}{field(available, setAvailable, "Enter available credit")}{field(cutoff, setCutoff, "Select default cut-off date")}{field(statementDate, setStatementDate, "Select default statement date")}{field(cardNotes, setCardNotes, "Add card notes")}{action("Save card", async () => { const id = accountId || (await createFinancialAccount(userId, deviceId, { name: cardName.trim(), kind: "credit_card", creditLimitCentavos: cents(limit) })).account.id; return saveCreditCard(userId, deviceId, { accountId: id, issuer: issuer || null, creditLimitMinor: cents(limit), availableCreditMinor: available ? cents(available) : null, defaultCutoffDate: cutoff, defaultStatementDate: statementDate, notes: cardNotes || null }); }, CREDIT_CARD_MESSAGES.saved)}</View>;
  if (!card) return <Text>{CREDIT_CARD_MESSAGES.error}</Text>;
  const cycle = cycles.find((item) => item.id === selectedCycleId); const settlementInstallment = installments.find((item) => item.settlementStatus === "active");
  const settlementEditor = settlementInstallment ? <View><Text>Early settlement</Text>{field(settlementDate, setSettlementDate, "Settlement date")}{field(settlementAmount, setSettlementAmount, "Settlement amount")}{field(settlementFee, setSettlementFee, "Pre-termination fee")}{field(settlementStatus, setSettlementStatus, "Settlement status")}{action("Request settlement", () => requestCreditCardSettlement(userId, deviceId, { installmentId: settlementInstallment.id, settlementDate, remainingPrincipalMinor: settlementInstallment.remainingPrincipalMinor, settlementAmountMinor: cents(settlementAmount), preterminationFeeMinor: cents(settlementFee) }), CREDIT_CARD_MESSAGES.settlementPending)}</View> : null;
  return <View style={{ gap: 12 }}><Pressable accessibilityLabel="Back to credit cards" onPress={onBack}><Text>Back to credit cards</Text></Pressable><Text style={{ fontSize: 24, fontWeight: "800" }}>{card.issuer || "Credit card"}</Text><Text>Limit {money(card.creditLimitMinor)} · Available {money(card.availableCreditMinor)}</Text>{error && <Text>{error}</Text>}{success && <Text>{success}</Text>}{confirmCardDelete ? <View><Text>This credit card and its debt-management details will be removed from active views. Existing account history remains available.</Text><Pressable accessibilityLabel="Cancel credit card deletion" onPress={() => setConfirmCardDelete(false)}><Text>Cancel</Text></Pressable>{action("Confirm delete credit card", async () => { await deleteCreditCard(userId, deviceId, card.accountId); onBack?.(); }, "Credit card removed from active views.")}</View> : <Pressable accessibilityLabel="Delete credit card" onPress={() => setConfirmCardDelete(true)}><Text style={{ color: "#D9001F" }}>Delete credit card</Text></Pressable>}{settlementEditor}
    <Text style={{ fontWeight: "800" }}>Billing cycles</Text>{cycles.length === 0 ? <Text>No billing cycles are recorded for this card. Add a billing cycle to track its statement activity.</Text> : cycles.map((item) => <Pressable key={item.id} accessibilityLabel={`Select cycle ${item.id}`} onPress={() => setSelectedCycleId(item.id)}><Text>{selectedCycleId === item.id ? "● " : "○ "}{item.cycleStartDate} to {item.cutoffDate}</Text><Text>Minimum due {money(item.minimumDueMinor)} · Charges {money(item.statementBalanceMinor ?? item.estimatedStatementBalanceMinor)} · Due {item.dueDate ?? "Not recorded"}</Text>{item.statementId == null && item.estimatedStatementBalanceMinor > 0 ? <Text>{CREDIT_CARD_MESSAGES.estimated}</Text> : null}{item.statementExpected ? <Text>Your statement for {card.issuer || "this card"} should be available today. Record it to update your payment requirement.</Text> : null}<Text>Payment status {item.paymentStatus ?? "Not recorded"} · Credit balance {money(item.creditBalanceMinor)}</Text></Pressable>)}
    {cycles.length > 0 && !cycle && <Text>Select a billing cycle before recording statement, payment, or credit activity.</Text>}{field(cycleStart, setCycleStart, "Select billing-cycle start date")}{field(cycleCutoff, setCycleCutoff, "Select cut-off date")}{field(cycleStatement, setCycleStatement, "Select statement date")}{action("Add billing cycle", () => createCreditCardCycle(userId, deviceId, { accountId: card.accountId, cycleStartDate: cycleStart, cutoffDate: cycleCutoff, statementDate: cycleStatement }), "Your billing cycle was recorded.")}
    {cycle && <>{field(statementBalance, setStatementBalance, "Statement balance")}{field(minimumDue, setMinimumDue, "Minimum amount due")}{field(financeCharge, setFinanceCharge, "Finance charges or interest")}{field(dueDate, setDueDate, "Due date")}{action("Record authoritative statement", () => recordCreditCardStatement(userId, deviceId, { cycleId: cycle.id, statementBalanceMinor: cents(statementBalance), minimumDueMinor: cents(minimumDue), financeChargeMinor: financeCharge ? cents(financeCharge) : 0, dueDate }), "Your authoritative statement was recorded.")}</>}
    {cycle?.statementId && <><Text style={{ fontWeight: "800" }}>Repayment strategy and payment</Text>{(["pay_full", "pay_minimum", "custom"] as const).map((value) => <Pressable key={value} accessibilityLabel={`Repayment strategy ${value}`} onPress={() => setStrategy(value)}><Text>{strategy === value ? "●" : "○"} {value}</Text></Pressable>)}{strategy === "custom" && field(custom, setCustom, "Custom payment")}{action("Save repayment strategy", () => setCreditCardStatementStrategy(userId, deviceId, cycle.statementId!, strategy, strategy === "custom" ? cents(custom) : undefined), "Your repayment strategy was saved.")}{field(paymentAmount, setPaymentAmount, "Payment amount")}{field(paymentDate, setPaymentDate, "Payment date")}{field(paymentSourceAccount, setPaymentSourceAccount, "Source account (optional)")}{field(paymentSubcategory, setPaymentSubcategory, "Payment category (optional)")}{field(paymentNotes, setPaymentNotes, "Payment notes")}{action("Record payment", () => recordCreditCardPayment(userId, deviceId, { cycleId: cycle.id, statementId: cycle.statementId, amountMinor: cents(paymentAmount), paymentDate, sourceAccountId: paymentSourceAccount || null, subcategoryId: paymentSubcategory || null, notes: paymentNotes || undefined, clientMutationId: `payment:${cycle.id}:${paymentDate}:${paymentAmount}` }), "Your credit-card payment was recorded.")}{selector(paymentId, setPaymentId, "Select payment to recognize", payments.map((item) => ({ id: item.id, label: `${item.paymentDate} · ${money(item.amountMinor)}${item.issuerRecognized ? " · Recognized" : ""}` })))}{action("Recognize issuer payment", () => recognizeCreditCardPayment(userId, deviceId, paymentId), "Issuer payment recognition was recorded.")}{selector(applicationTarget, setApplicationTarget, "Select target charge", transactions.map((item) => ({ id: item.id, label: `${item.transaction_date} · ${item.merchant_name || item.counterparty_name || item.id} · ${money(item.amount_centavos)}` })))}{field(applicationAmount, setApplicationAmount, "Credit application amount")}{field(applicationDate, setApplicationDate, "Application date")}{action("Apply credit balance", () => applyCreditCardBalance(userId, deviceId, { paymentId, targetTransactionId: applicationTarget, amountMinor: cents(applicationAmount), appliedDate: applicationDate, clientMutationId: `application:${paymentId}:${applicationTarget}:${applicationAmount}` }), "The credit balance was applied to the target charge.")}</>}
    <Text style={{ fontWeight: "800" }}>Add installment</Text>{field(installmentDescription, setInstallmentDescription, "Installment description")}{field(installmentOriginal, setInstallmentOriginal, "Original principal")}{field(installmentRemaining, setInstallmentRemaining, "Remaining principal")}{field(installmentTerm, setInstallmentTerm, "Term (months)")}{field(installmentMonths, setInstallmentMonths, "Remaining months")}{field(installmentAmortization, setInstallmentAmortization, "Monthly amortization")}{field(installmentRate, setInstallmentRate, "Interest rate (basis points)")}{action("Create installment", () => createCreditCardInstallment(userId, deviceId, { accountId: card.accountId, description: installmentDescription, originalPrincipalMinor: cents(installmentOriginal), remainingPrincipalMinor: cents(installmentRemaining), termMonths: Number(installmentTerm), remainingMonths: Number(installmentMonths), monthlyAmortizationMinor: cents(installmentAmortization), interestRateBps: Number(installmentRate || 0), interestType: installmentInterestType }), "Your installment was recorded.")}{installments.length > 0 && <><Text style={{ fontWeight: "800" }}>Installments</Text>{installments.map((item) => <View key={item.id}><Text>{item.description}: {money(item.remainingPrincipalMinor)} remaining, {item.remainingMonths} months · {item.settlementStatus}</Text>{item.settlementStatus === "settlement_requested" ? <Text>{CREDIT_CARD_MESSAGES.settlementPending}</Text> : item.settlementStatus === "completed" ? <Text>{CREDIT_CARD_MESSAGES.settlementRecognized}</Text> : <>{action("Request early settlement", () => requestCreditCardSettlement(userId, deviceId, { installmentId: item.id, settlementDate: today(), remainingPrincipalMinor: item.remainingPrincipalMinor, settlementAmountMinor: item.remainingPrincipalMinor }), CREDIT_CARD_MESSAGES.settlementPending)}{selector(settlementId, setSettlementId, "Select settlement to recognize", settlements.filter((settlement) => settlement.installmentId === item.id && settlement.status === "requested").map((settlement) => ({ id: settlement.id, label: `${settlement.settlementDate} · ${money(settlement.settlementAmountMinor)}` })))}{action("Recognize issuer settlement", () => recognizeCreditCardSettlement(userId, deviceId, settlementId), CREDIT_CARD_MESSAGES.settlementRecognized)}</>}</View>)}</>}
  </View>;
}
