import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, TextInput, View } from "react-native";
import { createDebt, deleteDebt, getDebtStrategy, listDebts, updateDebtStrategy, type Debt } from "../../local-db/repositories/debts";
import { DEBT_PRESETS, getDebtPreset } from "./presets";
import { calculateDebtPlan } from "./debtLogic";

type Props = { userId: string; deviceId: string; onSyncRequested?: () => Promise<void>; onPaymentRequested?: (debtId: string) => void };
const today = () => new Date().toISOString().slice(0, 10);

export default function DebtManagerScreen({ userId, deviceId, onSyncRequested, onPaymentRequested }: Props) {
  const [debts, setDebts] = useState<Debt[]>([]); const [strategy, setStrategy] = useState<"snowball" | "avalanche">("avalanche");
  const [name, setName] = useState(""); const [balance, setBalance] = useState(""); const [minimum, setMinimum] = useState(""); const [presetKey, setPresetKey] = useState(DEBT_PRESETS[0]!.key); const [showCreate, setShowCreate] = useState(false); const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { setDebts(await listDebts(userId)); setStrategy(await getDebtStrategy(userId)); } catch { setError("Debt data could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [userId]);
  async function save() { setError(null); try { await createDebt(userId, deviceId, { name, lenderName: null, presetKey, originalBalanceMinor: Math.round(Number(balance) * 100), annualInterestRateBps: 0, minimumPaymentMinor: Math.round(Number(minimum || 0) * 100), paymentFrequency: "monthly", nextDueDate: null, maturityDate: null, targetPayoffDate: null, interestPeriod: null, interestMethod: null, presetData: {}, notes: null }); setName(""); setBalance(""); setMinimum(""); setShowCreate(false); await load(); await onSyncRequested?.(); } catch (e) { setError(e instanceof Error ? e.message : "Debt could not be saved."); } }
  async function changeStrategy(value: "snowball" | "avalanche") { setStrategy(value); await updateDebtStrategy(userId, deviceId, value); await onSyncRequested?.(); }
  const plan = calculateDebtPlan(debts.map((debt) => ({ id: debt.id, balanceMinor: debt.currentBalanceMinor, minimumPaymentMinor: debt.minimumPaymentMinor, annualInterestRateBps: debt.annualInterestRateBps, nextDueDate: debt.nextDueDate, targetPayoffDate: debt.targetPayoffDate, overdue: false })), 0, strategy, [], today());
  return <View style={{ gap: 14 }}>
    <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><View><Text style={{ fontFamily: "Manrope", fontWeight: "800", fontSize: 20, color: "#1B1C1A" }}>Debt Manager</Text><Text style={{ fontFamily: "Manrope", fontSize: 12, color: "#6B7A6F" }}>Flat, offline-first debt planning</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Create debt" onPress={() => setShowCreate(true)} style={{ backgroundColor: "#013220", borderRadius: 12, padding: 12 }}><Text style={{ color: "#fff", fontWeight: "700" }}>Add</Text></Pressable></View>
    <View style={{ backgroundColor: "#F1F0EB", borderRadius: 16, padding: 14 }}><Text style={{ fontWeight: "700", color: "#1B1C1A" }}>Global strategy</Text><View style={{ flexDirection: "row", gap: 8, marginTop: 10 }}>{(["snowball", "avalanche"] as const).map((value) => <Pressable key={value} onPress={() => void changeStrategy(value)} accessibilityRole="radio" accessibilityState={{ selected: strategy === value }} style={{ backgroundColor: strategy === value ? "#0E6D46" : "#fff", padding: 10, borderRadius: 10 }}><Text style={{ color: strategy === value ? "#fff" : "#414942", textTransform: "capitalize" }}>{value}</Text></Pressable>)}</View><Text style={{ marginTop: 10, color: "#6B7A6F", fontSize: 12 }}>{plan.requiredTotalMinor / 100} required this cycle · set a monthly budget in Budgeting to allocate surplus.</Text></View>
    {showCreate ? <View style={{ backgroundColor: "#F7F0E1", borderRadius: 16, padding: 14, gap: 10 }}><Text style={{ fontWeight: "700" }}>New debt</Text><TextInput value={name} onChangeText={setName} placeholder="Debt name" style={{ backgroundColor: "#fff", padding: 12, borderRadius: 10 }} /><TextInput value={balance} onChangeText={setBalance} placeholder="Current balance (PHP)" keyboardType="decimal-pad" style={{ backgroundColor: "#fff", padding: 12, borderRadius: 10 }} /><TextInput value={minimum} onChangeText={setMinimum} placeholder="Minimum payment (PHP)" keyboardType="decimal-pad" style={{ backgroundColor: "#fff", padding: 12, borderRadius: 10 }} /><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{DEBT_PRESETS.map((preset) => <Pressable key={preset.key} onPress={() => setPresetKey(preset.key)} style={{ padding: 8, borderRadius: 8, backgroundColor: presetKey === preset.key ? "#0E6D46" : "#fff" }}><Text style={{ fontSize: 11, color: presetKey === preset.key ? "#fff" : "#414942" }}>{preset.label}</Text></Pressable>)}</View><View style={{ flexDirection: "row", gap: 8 }}><Pressable onPress={() => setShowCreate(false)} style={{ padding: 12 }}><Text>Cancel</Text></Pressable><Pressable onPress={() => void save()} style={{ backgroundColor: "#013220", padding: 12, borderRadius: 10 }}><Text style={{ color: "#fff", fontWeight: "700" }}>Save offline</Text></Pressable></View></View> : null}
    {error ? <Text style={{ color: "#D9001F" }}>{error}</Text> : null}{loading ? <ActivityIndicator color="#0E6D46" /> : debts.length === 0 ? <Text style={{ color: "#6B7A6F" }}>No debts yet.</Text> : debts.map((debt) => <View key={debt.id} style={{ backgroundColor: "#F1F0EB", borderRadius: 16, padding: 14 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><View><Text style={{ fontWeight: "800", color: "#1B1C1A" }}>{debt.name}</Text><Text style={{ color: "#6B7A6F", fontSize: 12 }}>{getDebtPreset(debt.presetKey).label}</Text></View><Text style={{ fontWeight: "800", color: "#013220" }}>₱{(debt.currentBalanceMinor / 100).toLocaleString("en-PH", { minimumFractionDigits: 2 })}</Text></View><Text style={{ color: "#6B7A6F", fontSize: 12, marginTop: 6 }}>Minimum ₱{(debt.minimumPaymentMinor / 100).toLocaleString("en-PH", { minimumFractionDigits: 2 })}</Text>{confirmDeleteId === debt.id ? <View style={{ marginTop: 10, gap: 8 }}><Text style={{ color: "#D9001F", fontSize: 12 }}>Delete this debt? Payment history remains locally readable.</Text><View style={{ flexDirection: "row", gap: 12 }}><Pressable onPress={() => setConfirmDeleteId(null)}><Text>Cancel</Text></Pressable><Pressable onPress={() => { void deleteDebt(userId, deviceId, debt.id, true).then(() => { setConfirmDeleteId(null); return load(); }); }}><Text style={{ color: "#D9001F", fontWeight: "700" }}>Confirm delete</Text></Pressable></View></View> : <View style={{ flexDirection: "row", gap: 14, marginTop: 10 }}><Pressable onPress={() => onPaymentRequested?.(debt.id)}><Text style={{ color: "#0E6D46", fontWeight: "700" }}>Record payment</Text></Pressable><Pressable onPress={() => setConfirmDeleteId(debt.id)}><Text style={{ color: "#D9001F", fontWeight: "700" }}>Delete</Text></Pressable></View>}</View>)}
  </View>;
}
