import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, TextInput, View } from "react-native";
import { getCurrentBudgetDraft } from "../../local-db/repositories/budgets";
import { createDebt, deleteDebt, getDebtStrategy, listCurrentDebtPaymentTotals, listDebtPriorities, listDebts, setDebtPriorities, updateDebt, updateDebtStrategy, type Debt } from "../../local-db/repositories/debts";
import { DEBT_PRESETS, getDebtPreset } from "./presets";
import { calculateDebtPlan, forecastDebtFreeMonths } from "./debtLogic";

type Props = { userId: string; deviceId: string; onSyncRequested?: () => Promise<void>; onPaymentRequested?: (debtId: string) => void };
const today = () => new Date().toISOString().slice(0, 10);
const money = (minor: number) => `₱${(minor / 100).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;

export default function DebtManagerScreen({ userId, deviceId, onSyncRequested, onPaymentRequested }: Props) {
  const [debts, setDebts] = useState<Debt[]>([]);
  const [priorities, setPriorities] = useState<string[]>([]);
  const [paidByDebt, setPaidByDebt] = useState<Record<string, number>>({});
  const [debtBudgetMinor, setDebtBudgetMinor] = useState(0);
  const [hasCurrentBudget, setHasCurrentBudget] = useState(false);
  const [strategy, setStrategy] = useState<"snowball" | "avalanche">("avalanche");
  const [name, setName] = useState(""); const [balance, setBalance] = useState(""); const [minimum, setMinimum] = useState(""); const [presetKey, setPresetKey] = useState(DEBT_PRESETS[0]!.key); const [editingId, setEditingId] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false); const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);
    try {
      const [nextDebts, nextPriorities, nextStrategy, currentBudget] = await Promise.all([listDebts(userId), listDebtPriorities(userId), getDebtStrategy(userId), getCurrentBudgetDraft(userId, today())]);
      const paymentTotals = await listCurrentDebtPaymentTotals(userId, today().slice(0, 7));
      setDebts(nextDebts); setPriorities(nextPriorities); setStrategy(nextStrategy); setDebtBudgetMinor(currentBudget?.debtBudgetMinor ?? 0); setHasCurrentBudget(Boolean(currentBudget)); setPaidByDebt(paymentTotals);
    } catch { setError("Debt data could not be loaded."); } finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, [userId]);

  async function save() { setError(null); try { const current = editingId ? debts.find((debt) => debt.id === editingId) : null; const input = { name, lenderName: current?.lenderName ?? null, presetKey, originalBalanceMinor: current?.originalBalanceMinor ?? Math.round(Number(balance) * 100), currentBalanceMinor: Math.round(Number(balance) * 100), annualInterestRateBps: current?.annualInterestRateBps ?? 0, minimumPaymentMinor: Math.round(Number(minimum || 0) * 100), paymentFrequency: current?.paymentFrequency ?? "monthly", nextDueDate: current?.nextDueDate ?? null, maturityDate: current?.maturityDate ?? null, targetPayoffDate: current?.targetPayoffDate ?? null, interestPeriod: current?.interestPeriod ?? null, interestMethod: current?.interestMethod ?? null, presetData: current?.presetData ?? {}, notes: current?.notes ?? null }; if (editingId) await updateDebt(userId, deviceId, editingId, input); else await createDebt(userId, deviceId, input); setName(""); setBalance(""); setMinimum(""); setEditingId(null); setShowCreate(false); await load(); await onSyncRequested?.(); } catch (e) { setError(e instanceof Error ? e.message : "Debt could not be saved."); } }
  function edit(debt: Debt) { setEditingId(debt.id); setName(debt.name); setBalance(String(debt.currentBalanceMinor / 100)); setMinimum(String(debt.minimumPaymentMinor / 100)); setPresetKey(debt.presetKey); setShowCreate(true); }
  async function movePriority(id: string, direction: -1 | 1) { const ordered = [...(priorities.length ? priorities : debts.map((debt) => debt.id))]; const index = ordered.indexOf(id); const next = index + direction; if (index < 0 || next < 0 || next >= ordered.length) return; [ordered[index], ordered[next]] = [ordered[next]!, ordered[index]!]; await setDebtPriorities(userId, deviceId, ordered); setPriorities(ordered); }
  async function changeStrategy(value: "snowball" | "avalanche") { setStrategy(value); await updateDebtStrategy(userId, deviceId, value); await onSyncRequested?.(); }

  const plan = calculateDebtPlan({ debts: debts.map((debt) => ({ id: debt.id, balanceMinor: debt.currentBalanceMinor, minimumPaymentMinor: debt.minimumPaymentMinor, annualInterestRateBps: debt.annualInterestRateBps, paymentFrequency: debt.paymentFrequency, nextDueDate: debt.nextDueDate, targetPayoffDate: debt.targetPayoffDate, paidPaymentMinor: paidByDebt[debt.id] ?? 0, overdue: Boolean(debt.nextDueDate && debt.nextDueDate < today()) })), debtBudgetMinor, strategy, priorities, asOfDate: today() });
  const forecastMonths = forecastDebtFreeMonths(plan.allocations, debtBudgetMinor, strategy, priorities);

  return <View style={{ gap: 14 }}>
    <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><View><Text style={{ fontFamily: "Manrope", fontWeight: "800", fontSize: 20, color: "#1B1C1A" }}>Debt Manager</Text><Text style={{ fontFamily: "Manrope", fontSize: 12, color: "#6B7A6F" }}>Flat, offline-first debt planning</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Create debt" onPress={() => { setEditingId(null); setShowCreate(true); }} style={{ backgroundColor: "#013220", borderRadius: 12, padding: 12 }}><Text style={{ color: "#fff", fontWeight: "700" }}>Add</Text></Pressable></View>
    {!hasCurrentBudget ? <View style={{ backgroundColor: "#FFF4D6", borderRadius: 12, padding: 12 }}><Text style={{ color: "#6B4E00", fontWeight: "700" }}>Set up a current monthly budget to plan debt payments.</Text><Text style={{ color: "#6B4E00", fontSize: 12, marginTop: 4 }}>Available debt budget is currently ₱0.</Text></View> : null}
    <View style={{ backgroundColor: "#F1F0EB", borderRadius: 16, padding: 14, gap: 6 }}><Text style={{ fontWeight: "700", color: "#1B1C1A" }}>Plan this cycle</Text><Text>Debt budget: {money(debtBudgetMinor)}</Text><Text>Required payments: {money(plan.requiredTotalMinor)}</Text><Text>Surplus: {money(plan.surplusMinor)} · Shortfall: {money(plan.shortfallMinor)}</Text><Text style={{ color: "#6B7A6F", fontSize: 12 }}>Principal-only estimate: {forecastMonths === null ? "not available" : `${forecastMonths} month${forecastMonths === 1 ? "" : "s"} to debt-free`}</Text></View>
    <View style={{ backgroundColor: "#F1F0EB", borderRadius: 16, padding: 14 }}><Text style={{ fontWeight: "700", color: "#1B1C1A" }}>Global strategy</Text><View style={{ flexDirection: "row", gap: 8, marginTop: 10 }}>{(["snowball", "avalanche"] as const).map((value) => <Pressable key={value} onPress={() => void changeStrategy(value)} accessibilityRole="radio" accessibilityState={{ selected: strategy === value }} style={{ backgroundColor: strategy === value ? "#0E6D46" : "#fff", padding: 10, borderRadius: 10 }}><Text style={{ color: strategy === value ? "#fff" : "#414942", textTransform: "capitalize" }}>{value}</Text></Pressable>)}</View></View>
    {showCreate ? <View style={{ backgroundColor: "#F7F0E1", borderRadius: 16, padding: 14, gap: 10 }}><Text style={{ fontWeight: "700" }}>{editingId ? "Edit debt" : "New debt"}</Text><TextInput value={name} onChangeText={setName} placeholder="Debt name" style={{ backgroundColor: "#fff", padding: 12, borderRadius: 10 }} /><TextInput value={balance} onChangeText={setBalance} placeholder="Current balance (PHP)" keyboardType="decimal-pad" style={{ backgroundColor: "#fff", padding: 12, borderRadius: 10 }} /><TextInput value={minimum} onChangeText={setMinimum} placeholder="Minimum payment (PHP)" keyboardType="decimal-pad" style={{ backgroundColor: "#fff", padding: 12, borderRadius: 10 }} /><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{DEBT_PRESETS.map((preset) => <Pressable key={preset.key} onPress={() => setPresetKey(preset.key)} style={{ padding: 8, borderRadius: 8, backgroundColor: presetKey === preset.key ? "#0E6D46" : "#fff" }}><Text style={{ fontSize: 11, color: presetKey === preset.key ? "#fff" : "#414942" }}>{preset.label}</Text></Pressable>)}</View><View style={{ flexDirection: "row", gap: 8 }}><Pressable onPress={() => { setEditingId(null); setShowCreate(false); }} style={{ padding: 12 }}><Text>Cancel</Text></Pressable><Pressable onPress={() => void save()} style={{ backgroundColor: "#013220", padding: 12, borderRadius: 10 }}><Text style={{ color: "#fff", fontWeight: "700" }}>Save offline</Text></Pressable></View></View> : null}
    {error ? <Text style={{ color: "#D9001F" }}>{error}</Text> : null}{loading ? <ActivityIndicator color="#0E6D46" /> : debts.length === 0 ? <Text style={{ color: "#6B7A6F" }}>No debts yet.</Text> : debts.map((debt) => { const allocation = plan.allocations.find((item) => item.id === debt.id); return <View key={debt.id} style={{ backgroundColor: "#F1F0EB", borderRadius: 16, padding: 14 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><View><Text style={{ fontWeight: "800", color: "#1B1C1A" }}>{debt.name}</Text><Text style={{ color: "#6B7A6F", fontSize: 12 }}>{getDebtPreset(debt.presetKey).label}</Text></View><Text style={{ fontWeight: "800", color: "#013220" }}>{money(debt.currentBalanceMinor)}</Text></View><Text style={{ color: "#6B7A6F", fontSize: 12, marginTop: 6 }}>Required {money(allocation?.requiredPaymentMinor ?? 0)} · Allocated {money(allocation?.allocatedPaymentMinor ?? 0)}</Text><Text style={{ color: allocation?.status === "Behind" ? "#D9001F" : "#0E6D46", fontWeight: "700", marginTop: 4 }}>{allocation?.status ?? "On Schedule"}{allocation?.extraPaymentMinor ? ` · Extra ${money(allocation.extraPaymentMinor)}` : ""}</Text>{confirmDeleteId === debt.id ? <View style={{ marginTop: 10, gap: 8 }}><Text style={{ color: "#D9001F", fontSize: 12 }}>Delete this debt? Payment history remains locally readable.</Text><View style={{ flexDirection: "row", gap: 12 }}><Pressable onPress={() => setConfirmDeleteId(null)}><Text>Cancel</Text></Pressable><Pressable onPress={() => { void deleteDebt(userId, deviceId, debt.id, true).then(() => { setConfirmDeleteId(null); return load(); }); }}><Text style={{ color: "#D9001F", fontWeight: "700" }}>Confirm delete</Text></Pressable></View></View> : <View style={{ flexDirection: "row", gap: 14, marginTop: 10 }}><Pressable onPress={() => onPaymentRequested?.(debt.id)}><Text style={{ color: "#0E6D46", fontWeight: "700" }}>Record payment</Text></Pressable><Pressable onPress={() => edit(debt)}><Text style={{ color: "#0E6D46", fontWeight: "700" }}>Edit</Text></Pressable><Pressable onPress={() => void movePriority(debt.id, -1)}><Text style={{ color: "#0E6D46", fontWeight: "700" }}>Up</Text></Pressable><Pressable onPress={() => void movePriority(debt.id, 1)}><Text style={{ color: "#0E6D46", fontWeight: "700" }}>Down</Text></Pressable><Pressable onPress={() => setConfirmDeleteId(debt.id)}><Text style={{ color: "#D9001F", fontWeight: "700" }}>Delete</Text></Pressable></View>}</View>; })}
  </View>;
}
