import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, View } from "react-native";
import { getSavingsAllocationStrategy, saveSavingsAllocationStrategy, type SavingsAllocationStrategy } from "../../local-db/repositories/savingsAllocationPreferences";
import { getCurrentSavingsEnvelopeAllocation } from "./savingsEnvelopeAllocationQueries";
import type { SavingsEnvelopeAllocation, SavingsAllocationProposal } from "./savingsEnvelopeAllocation";

const P = { card: "#F1F0EB", ink: "#1B1C1A", muted: "#6B7A6F", brand: "#013220", line: "#EAEAE6", error: "#D9001F", white: "#FFFFFF" } as const;
const money = (amount: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(amount / 100);
const reason = (proposal: SavingsAllocationProposal) => proposal.reason === "emergency_fund_required" ? "Emergency Fund priority" : proposal.reason === "scheduled_required" ? "Scheduled contribution" : proposal.reason === "avalanche_surplus" ? "Avalanche surplus" : proposal.reason === "snowball_surplus" ? "Snowball surplus" : "No envelope remaining";

export default function SavingsAllocationReview({ userId, deviceId, onApprove }: { userId: string; deviceId: string; onApprove: (goalId: string, amountCentavos: number) => void }) {
  const [allocation, setAllocation] = useState<SavingsEnvelopeAllocation | null>(null);
  const [strategy, setStrategy] = useState<SavingsAllocationStrategy>("avalanche");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const today = new Date().toISOString().slice(0, 10);
  async function load() { setLoading(true); try { const [nextAllocation, nextStrategy] = await Promise.all([getCurrentSavingsEnvelopeAllocation(userId, today), getSavingsAllocationStrategy(userId)]); setAllocation(nextAllocation); setStrategy(nextStrategy); } finally { setLoading(false); } }
  useEffect(() => { load().catch(() => setAllocation(null)); }, [userId]);
  async function selectStrategy(next: SavingsAllocationStrategy) { setSaving(true); try { await saveSavingsAllocationStrategy(userId, deviceId, next); setStrategy(next); await load(); } finally { setSaving(false); } }
  if (loading) return <View style={{ minHeight: 180, alignItems: "center", justifyContent: "center" }}><ActivityIndicator color={P.brand} /></View>;
  if (!allocation) return <View style={{ backgroundColor: P.card, borderColor: P.line, borderWidth: 1, borderRadius: 14, gap: 8, padding: 15 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 16, fontWeight: "800" }}>Savings allocation</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Create a current budget with a Savings Envelope to review goal allocations.</Text></View>;
  return <View style={{ gap: 12 }}><View style={{ backgroundColor: P.card, borderColor: P.line, borderWidth: 1, borderRadius: 14, gap: 6, padding: 15 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 19, fontWeight: "800" }}>Savings allocation</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Envelope: {money(allocation.envelopeCentavos)} · Required: {money(allocation.requiredCentavos)}</Text><Text style={{ color: allocation.shortfallCentavos > 0 ? P.error : P.brand, fontFamily: "Manrope", fontSize: 12, fontWeight: "700" }}>{allocation.shortfallCentavos > 0 ? `Shortfall: ${money(allocation.shortfallCentavos)}` : `${money(allocation.unallocatedCentavos)} left unallocated`}</Text></View><View style={{ flexDirection: "row", gap: 8 }}>{(["avalanche", "snowball"] as const).map((option) => <Pressable key={option} accessibilityRole="button" accessibilityLabel={`Use ${option} savings allocation`} disabled={saving} onPress={() => { selectStrategy(option).catch(() => {}); }} style={{ flex: 1, alignItems: "center", borderColor: strategy === option ? P.brand : P.line, borderRadius: 10, borderWidth: 1, padding: 11, backgroundColor: strategy === option ? P.brand : P.white }}><Text style={{ color: strategy === option ? P.white : P.ink, fontFamily: "Manrope", fontSize: 12, fontWeight: "700" }}>{option === "avalanche" ? "Avalanche" : "Snowball"}</Text></Pressable>)}</View><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 11 }}>This is a proposal. Reviewing a row opens a contribution; no money moves until you save it.</Text>{allocation.proposals.length === 0 ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>No active goals with a due contribution are eligible this cycle.</Text> : allocation.proposals.map((proposal) => <View key={proposal.id} style={{ backgroundColor: P.card, borderColor: P.line, borderWidth: 1, borderRadius: 13, gap: 5, padding: 14 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontWeight: "800" }}>{proposal.name}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>{proposal.state.replace("_", " ")} · {reason(proposal)}</Text><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 13, fontWeight: "700" }}>Proposed contribution: {money(proposal.proposedTotalCentavos)}</Text>{proposal.proposedTotalCentavos > 0 ? <Pressable accessibilityRole="button" accessibilityLabel={`Review contribution for ${proposal.name}`} onPress={() => onApprove(proposal.id, proposal.proposedTotalCentavos)} style={{ alignItems: "center", backgroundColor: P.brand, borderRadius: 9, marginTop: 5, padding: 10 }}><Text style={{ color: P.white, fontFamily: "Manrope", fontWeight: "700", fontSize: 12 }}>Review contribution</Text></Pressable> : null}</View>)}</View>;
}
