import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, View } from "react-native";
import { archiveSavingsGoal, deleteSavingsGoal, getSavingsGoal, listSavingsGoals, restoreSavingsGoal, type SavingsGoal } from "../../local-db/repositories/savingsGoals";
import { SAVINGS_GOAL_PRIORITY_LABELS, SAVINGS_GOAL_TYPE_LABELS } from "./constants";
import SavingsGoalForm from "./SavingsGoalForm";
import { listFinancialAccounts, type FinancialAccount } from "../../local-db/repositories/financialFoundations";
import { getMinimumContributionPerOccurrence, type ScheduledSavingsGoal } from "./contributionSchedule";
import { listSavingsGoalActivities } from "../../local-db/repositories/savingsGoalActivities";
import type { SavingsActivity } from "./types";
import { getSavingsAccountDetails, type SavingsAccountDetails } from "../../local-db/repositories/savingsAccountDetails";

const P = { card: "#F1F0EB", ink: "#1B1C1A", muted: "#6B7A6F", brand: "#013220", line: "#EAEAE6", error: "#D9001F", white: "#FFFFFF" } as const;
type Props = { userId: string; deviceId: string; syncVersion?: number; onRecordActivity?: (goalId: string, kind: "contribution" | "withdrawal") => void; onOpenTransaction?: (transactionId: string) => void };
type Page = "list" | "create" | "detail" | "account-detail" | "edit";
const money = (amount: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(amount / 100);
const savingsAccountTypeLabel = (account: FinancialAccount) => account.savingsAccountType === "personal_savings" ? "Personal Savings" : account.savingsAccountType === "high_yield_savings" ? "HYSA" : account.savingsAccountType === "time_deposit" ? "Time Deposit" : "Savings";

export default function SavingsGoalsScreen({ userId, deviceId, syncVersion = 0, onRecordActivity, onOpenTransaction }: Props) {
  const [goals, setGoals] = useState<SavingsGoal[]>([]);
  const [savingsAccounts, setSavingsAccounts] = useState<FinancialAccount[]>([]);
  const [selected, setSelected] = useState<SavingsGoal | null>(null);
  const [selectedAccount, setSelectedAccount] = useState<FinancialAccount | null>(null);
  const [selectedAccountDetails, setSelectedAccountDetails] = useState<SavingsAccountDetails | null>(null);
  const [activities, setActivities] = useState<SavingsActivity[]>([]);
  const [page, setPage] = useState<Page>("list");
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [confirmingArchive, setConfirmingArchive] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [view, setView] = useState<"active" | "archived">("active");
  async function load() { setLoading(true); try { const [nextGoals, accounts] = await Promise.all([listSavingsGoals(userId, view), listFinancialAccounts(userId)]); setGoals(nextGoals); setSavingsAccounts(accounts.filter((account) => account.kind === "savings" && account.status === "active")); setMessage(null); } catch { setMessage("Your savings information could not be loaded. Check your connection and try again."); } finally { setLoading(false); } }
  useEffect(() => { load().catch(() => {}); }, [userId, syncVersion, view]);
  async function openGoal(id: string) { const [goal, nextActivities] = await Promise.all([getSavingsGoal(userId, id), listSavingsGoalActivities(userId, id)]); if (goal) { setSelected(goal); setActivities(nextActivities); setConfirmingDelete(false); setConfirmingArchive(false); setPage("detail"); } }
  async function openSavingsAccount(account: FinancialAccount) { const details = await getSavingsAccountDetails(userId, account.id); setSelectedAccount(account); setSelectedAccountDetails(details); setPage("account-detail"); }
  async function remove() { if (!selected) return; setDeleting(true); try { await deleteSavingsGoal(userId, deviceId, selected.id); await load(); setSelected(null); setPage("list"); } catch { setMessage("Your savings goal could not be deleted. Please try again."); } finally { setDeleting(false); } }
  async function archive() { if (!selected) return; setDeleting(true); try { await archiveSavingsGoal(userId, deviceId, selected.id); await load(); setSelected(null); setPage("list"); } catch { setMessage("Your savings goal could not be archived. Please try again."); } finally { setDeleting(false); } }
  async function restore() { if (!selected) return; setDeleting(true); try { await restoreSavingsGoal(userId, deviceId, selected.id); setView("active"); setSelected(null); setPage("list"); } catch { setMessage("Your savings goal could not be restored. Please try again."); } finally { setDeleting(false); } }
  if (page === "create" || page === "edit") return <SavingsGoalForm userId={userId} deviceId={deviceId} goal={page === "edit" ? selected ?? undefined : undefined} onCancel={() => setPage(selected ? "detail" : "list")} onSaved={(goal) => { setSelected(goal); load().catch(() => {}); setPage("detail"); }} />;
  if (loading) return <View style={{ minHeight: 180, alignItems: "center", justifyContent: "center" }}><ActivityIndicator color={P.brand} /></View>;
  if (page === "detail" && selected) {
    const today = new Date().toISOString().slice(0, 10);
    const minimum = getMinimumContributionPerOccurrence(selected as ScheduledSavingsGoal, today);
    const contributions = activities.filter((activity) => activity.kind === "contribution");
    const withdrawals = activities.filter((activity) => activity.kind === "withdrawal");
    const status = selected.status === "archived" ? "Archived" : selected.isAchieved ? "Achieved" : "Active";
    return <View style={{ gap: 14 }}>
    <View style={{ backgroundColor: P.card, borderColor: P.line, borderRadius: 14, borderWidth: 1, gap: 7, padding: 15 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 20, fontWeight: "800" }}>{selected.name}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>{SAVINGS_GOAL_TYPE_LABELS[selected.goalType]} · {SAVINGS_GOAL_PRIORITY_LABELS[selected.priority]} priority</Text><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 14, fontWeight: "700" }}>Current balance: {money(selected.currentAmountCentavos)}</Text><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 14, fontWeight: "700" }}>Target: {money(selected.targetAmountCentavos)}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Remaining: {money(selected.remainingAmountCentavos)} · {selected.progressPercent}% complete</Text><Text style={{ color: selected.status === "archived" ? P.muted : P.brand, fontFamily: "Manrope", fontSize: 12, fontWeight: "700" }}>Status: {status}</Text>{selected.notes ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Notes: {selected.notes}</Text> : null}{selected.targetDate ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Target date: {selected.targetDate}</Text> : null}{selected.nextContributionDate ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Next contribution: {selected.nextContributionDate} · Planned {money(selected.plannedContributionAmountCentavos)}</Text> : <Text style={{ color: P.error, fontFamily: "Manrope", fontSize: 12 }}>Add a contribution schedule to calculate your minimum needed amount.</Text>}{minimum !== null ? <Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 12, fontWeight: "700" }}>Minimum per contribution: {money(minimum)}</Text> : null}</View>
    {selected.status === "active" && selected.currentAmountCentavos < selected.targetAmountCentavos ? <Button label="Add contribution" onPress={() => onRecordActivity?.(selected.id, "contribution")} /> : null}
    {selected.status === "active" ? <Button label="Withdraw" secondary onPress={() => onRecordActivity?.(selected.id, "withdrawal")} /> : null}
    <SavingsActivityList title="Recent activity" activities={activities.slice(0, 5)} emptyMessage="This Goal Savings account has no recorded activity yet." onOpenTransaction={onOpenTransaction} />
    <SavingsActivityList title="Contributions" activities={contributions} emptyMessage="This Goal Savings account has no recorded contributions. Add a contribution to update its progress." onOpenTransaction={onOpenTransaction} />
    <SavingsActivityList title="Withdrawals" activities={withdrawals} emptyMessage="This Goal Savings account has no recorded withdrawals." onOpenTransaction={onOpenTransaction} />
    {selected.status === "active" ? <><Button label="Edit goal" onPress={() => setPage("edit")} />
    {confirmingArchive ? <View style={{ backgroundColor: "#F8EFDC", borderRadius: 12, gap: 10, padding: 13 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontWeight: "800" }}>Archive this savings goal?</Text><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 12 }}>Archived goals are kept with their history and can be restored later.</Text><Button label={deleting ? "Archiving..." : "Confirm archive"} disabled={deleting} onPress={() => { archive().catch(() => {}); }} /><Button label="Cancel" secondary onPress={() => setConfirmingArchive(false)} /></View> : <Button label="Archive goal" secondary onPress={() => setConfirmingArchive(true)} />}</> : <Button label={deleting ? "Restoring..." : "Restore goal"} disabled={deleting} onPress={() => { restore().catch(() => {}); }} />}
    {confirmingDelete ? <View style={{ backgroundColor: "#FFF0F2", borderRadius: 12, gap: 10, padding: 13 }}><Text style={{ color: P.error, fontFamily: "Manrope", fontWeight: "800" }}>Delete this savings goal?</Text><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 12 }}>This removes the goal and its history from your active list. This action cannot be undone.</Text><Button label={deleting ? "Deleting..." : "Confirm delete"} danger disabled={deleting} onPress={() => { remove().catch(() => {}); }} /><Button label="Cancel" secondary onPress={() => setConfirmingDelete(false)} /></View> : <Button label="Delete goal" danger onPress={() => setConfirmingDelete(true)} />}
   </View>;
  }
  if (page === "account-detail" && selectedAccount) return <SavingsAccountDetail account={selectedAccount} details={selectedAccountDetails} onBack={() => { setSelectedAccount(null); setSelectedAccountDetails(null); setPage("list"); }} />;
   const totalSavingsCentavos = savingsAccounts.reduce((total, account) => total + account.currentBalanceCentavos, 0) + goals.reduce((total, goal) => total + goal.currentAmountCentavos, 0);
   return <View style={{ gap: 14 }}><View><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 20, fontWeight: "800" }}>Savings</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Total saved: {money(totalSavingsCentavos)}</Text></View>{message ? <Text style={{ color: P.error }}>{message}</Text> : null}{savingsAccounts.length > 0 ? <View style={{ gap: 8 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 13, fontWeight: "800" }}>Savings accounts</Text>{savingsAccounts.map((account) => <Pressable key={account.id} accessibilityRole="button" accessibilityLabel={`Open ${account.name}`} onPress={() => { openSavingsAccount(account).catch(() => {}); }} style={{ backgroundColor: P.card, borderColor: P.line, borderRadius: 13, borderWidth: 1, gap: 4, padding: 14 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 15, fontWeight: "800" }}>{account.name}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>{savingsAccountTypeLabel(account)} · {money(account.currentBalanceCentavos)}</Text></Pressable>)}</View> : null}<View style={{ flexDirection: "row", gap: 8 }}><Button label="Active goals" secondary={view !== "active"} onPress={() => setView("active")} /><Button label="Completed goals" secondary={view !== "archived"} onPress={() => setView("archived")} /></View><View style={{ gap: 8 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 13, fontWeight: "800" }}>{view === "active" ? "Goal savings" : "Completed goal savings"}</Text>{goals.length === 0 ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>No {view === "active" ? "active" : "completed"} savings goals yet.</Text> : goals.map((goal) => <Pressable key={goal.id} accessibilityRole="button" accessibilityLabel={`Open ${goal.name}`} onPress={() => { openGoal(goal.id).catch(() => {}); }} style={{ backgroundColor: P.card, borderColor: P.line, borderRadius: 13, borderWidth: 1, gap: 5, padding: 14 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 15, fontWeight: "800" }}>{goal.name}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>{money(goal.currentAmountCentavos)} of {money(goal.targetAmountCentavos)}</Text></Pressable>)}</View>{view === "active" ? <Button label="Add savings goal" onPress={() => setPage("create")} /> : null}</View>;
}

function Button({ label, onPress, secondary, danger, disabled }: { label: string; onPress: () => void; secondary?: boolean; danger?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={{ backgroundColor: secondary ? P.white : danger ? P.error : P.brand, borderColor: P.line, borderRadius: 10, borderWidth: secondary ? 1 : 0, minHeight: 46, alignItems: "center", justifyContent: "center", opacity: disabled ? 0.6 : 1 }}><Text style={{ color: secondary ? P.ink : P.white, fontFamily: "Manrope", fontWeight: "700" }}>{label}</Text></Pressable>; }

function SavingsActivityList({ title, activities, emptyMessage, onOpenTransaction }: { title: string; activities: SavingsActivity[]; emptyMessage: string; onOpenTransaction?: (transactionId: string) => void }) {
  return <View style={{ gap: 8 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 13, fontWeight: "800" }}>{title}</Text>{activities.length === 0 ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>{emptyMessage}</Text> : activities.map((activity) => <Pressable key={activity.id} accessibilityRole="button" accessibilityLabel={`Open ${activity.kind} transaction`} onPress={() => onOpenTransaction?.(activity.transactionId)} disabled={!onOpenTransaction} style={{ backgroundColor: P.card, borderColor: P.line, borderRadius: 12, borderWidth: 1, gap: 3, opacity: onOpenTransaction ? 1 : 0.7, padding: 12 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 13, fontWeight: "700" }}>{activity.kind === "contribution" ? "Contribution" : "Withdrawal"} · {money(activity.amountCentavos)}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 11 }}>{activity.activityDate}{activity.notes ? ` · ${activity.notes}` : ""}</Text></Pressable>)}</View>;
}

function SavingsAccountDetail({ account, details, onBack }: { account: FinancialAccount; details: SavingsAccountDetails | null; onBack: () => void }) {
  const rate = details?.accountType === "high_yield_savings" ? details.effectiveInterestRateBps ?? details.baseInterestRateBps : details?.interestRateBps;
  return <View style={{ gap: 14 }}><View style={{ backgroundColor: P.card, borderColor: P.line, borderRadius: 14, borderWidth: 1, gap: 7, padding: 15 }}><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 20, fontWeight: "800" }}>{account.name}</Text><Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>{savingsAccountTypeLabel(account)}</Text><Text style={{ color: P.ink, fontFamily: "Manrope", fontSize: 14, fontWeight: "700" }}>Current balance: {money(account.currentBalanceCentavos)}</Text><Text style={{ color: account.status === "archived" ? P.muted : P.brand, fontFamily: "Manrope", fontSize: 12, fontWeight: "700" }}>Status: {account.status === "archived" ? "Archived" : "Active"}</Text>{account.institutionName ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Institution: {account.institutionName}</Text> : null}{account.openedOn ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Opening date: {account.openedOn}</Text> : null}{rate != null ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Interest rate: {(rate / 100).toFixed(2)}%</Text> : null}{details?.minimumBalanceCentavos != null ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Minimum balance: {money(details.minimumBalanceCentavos)}</Text> : null}{details?.maturityDate ? <Text style={{ color: P.muted, fontFamily: "Manrope", fontSize: 12 }}>Maturity date: {details.maturityDate}</Text> : null}{details?.earlyWithdrawalRule ? <Text style={{ color: P.error, fontFamily: "Manrope", fontSize: 12 }}>Early-withdrawal rule: {details.earlyWithdrawalRule}</Text> : null}</View><Button label="Back to savings" secondary onPress={onBack} /></View>;
}
