import React from "react";
import { fireEvent, render, waitFor } from "@testing-library/react-native";
import DebtManagerOverview from "../DebtManagerOverview";

const mockListFinancialAccounts = jest.fn(); const mockListDebtAccounts = jest.fn(); const mockArchiveDebtAccount = jest.fn(); const mockMarkDebtAccountDeleted = jest.fn(); const mockListDebtPayments = jest.fn(); const mockDeleteTransactionDebtPayment = jest.fn();
jest.mock("../../../local-db/repositories/financialFoundations", () => ({ listFinancialAccounts: (...args: unknown[]) => mockListFinancialAccounts(...args) }));
jest.mock("../../../local-db/repositories/debtAccounts", () => ({ listDebtAccounts: (...args: unknown[]) => mockListDebtAccounts(...args), archiveDebtAccount: (...args: unknown[]) => mockArchiveDebtAccount(...args), markDebtAccountDeleted: (...args: unknown[]) => mockMarkDebtAccountDeleted(...args) }));
jest.mock("../../../local-db/repositories/debtPayments", () => ({ listDebtPayments: (...args: unknown[]) => mockListDebtPayments(...args), deleteTransactionDebtPayment: (...args: unknown[]) => mockDeleteTransactionDebtPayment(...args) }));

const debt = { id: "debt-1", name: "Car loan", lenderName: "Bank A", type: "auto_loan", status: "active", progress: "no_payments", originalBalanceCentavos: 500000, currentBalanceCentavos: 450000, annualInterestRateBps: 650, minimumPaymentCentavos: 15000, paymentFrequency: "monthly", nextDueDate: "2026-10-01", maturityDate: null, targetPayoffDate: null, interestPeriod: "annual", interestMethod: "diminishing_balance", notes: null, typeSpecific: { startDate: "2026-01-01", feesCentavos: 0, penaltyInfo: null, termMonths: null }, hasPaymentHistory: false, archivedAt: null, paidOffAt: null, version: 1 };
describe("DebtManagerOverview non-credit-card debts", () => {
  beforeEach(() => { jest.clearAllMocks(); mockListFinancialAccounts.mockResolvedValue([]); mockListDebtAccounts.mockResolvedValue([debt]); mockListDebtPayments.mockResolvedValue([]); });
  it("groups debts by category and shows their payment activity", async () => { const view = render(<DebtManagerOverview userId="user-1" deviceId="device-1" onOpenCreditCards={jest.fn()} onRecordDebtPayment={jest.fn()} onEditDebtPayment={jest.fn()} />); expect(await view.findByText("Your debts")).toBeTruthy(); expect(view.getByText("Auto Loan · 1")).toBeTruthy(); expect(view.getByText("Car loan")).toBeTruthy(); expect(view.getByText("Recent payments")).toBeTruthy(); expect(view.getByText("Debt actions")).toBeTruthy(); });
  it("archives debt after explicit confirmation", async () => { mockArchiveDebtAccount.mockResolvedValue({ debt: { ...debt, status: "archived" } }); const view = render(<DebtManagerOverview userId="user-1" deviceId="device-1" onOpenCreditCards={jest.fn()} onRecordDebtPayment={jest.fn()} onEditDebtPayment={jest.fn()} />); await view.findByText("Your debts"); fireEvent.press(view.getByText("Archive debt")); fireEvent.press(view.getByText("Confirm archive")); await waitFor(() => expect(mockArchiveDebtAccount).toHaveBeenCalledWith("user-1", "device-1", "debt-1")); });
  it("shows three payments initially and expands the rest", async () => { const payments = ["08", "07", "06", "05"].map((day, index) => ({ id: `payment-${index}`, debt_account_id: "debt-1", transaction_id: `tx-${index}`, payment_date: `2026-09-${day}`, amount_centavos: 15000, notes: null, version: 1 })); mockListDebtPayments.mockResolvedValue(payments); const view = render(<DebtManagerOverview userId="user-1" deviceId="device-1" onOpenCreditCards={jest.fn()} onRecordDebtPayment={jest.fn()} onEditDebtPayment={jest.fn()} />); expect(await view.findByText("2026-09-08")).toBeTruthy(); expect(view.queryByText("2026-09-05")).toBeNull(); fireEvent.press(view.getByLabelText("Show all payments for Car loan")); expect(await view.findByText("2026-09-05")).toBeTruthy(); });
  it("edits and deletes payments from recent payment activity", async () => { const payment = { id: "payment-1", debt_account_id: "debt-1", transaction_id: "tx-1", payment_date: "2026-09-08", amount_centavos: 15000, notes: null, version: 1 }; const onEditDebtPayment = jest.fn(); mockListDebtPayments.mockResolvedValue([payment]); mockDeleteTransactionDebtPayment.mockResolvedValue(undefined); const view = render(<DebtManagerOverview userId="user-1" deviceId="device-1" onOpenCreditCards={jest.fn()} onRecordDebtPayment={jest.fn()} onEditDebtPayment={onEditDebtPayment} />); expect(await view.findByText("Recent payments")).toBeTruthy(); fireEvent.press(view.getByLabelText("Edit payment on 2026-09-08")); expect(onEditDebtPayment).toHaveBeenCalledWith(payment); fireEvent.press(view.getByLabelText("Delete payment on 2026-09-08")); fireEvent.press(view.getByText("Confirm delete")); await waitFor(() => expect(mockDeleteTransactionDebtPayment).toHaveBeenCalledWith("user-1", "device-1", "payment-1")); });
  it("lists paid debts in the Finished view instead of dropping them", async () => { const finishedDebt = { ...debt, status: "paid_off", progress: "finished", currentBalanceCentavos: 0, paidOffAt: "2026-09-08T12:00:00.000Z" }; mockListDebtAccounts.mockImplementation((_userId: string, visibility = "active") => Promise.resolve(visibility === "finished" ? [finishedDebt] : [debt])); const view = render(<DebtManagerOverview userId="user-1" deviceId="device-1" onOpenCreditCards={jest.fn()} onRecordDebtPayment={jest.fn()} onEditDebtPayment={jest.fn()} />); await view.findByText("Your debts"); fireEvent.press(view.getByLabelText("Show finished debts")); await waitFor(() => expect(mockListDebtAccounts).toHaveBeenLastCalledWith("user-1", "finished")); expect(view.getByText("Paid off")).toBeTruthy(); expect(view.queryByLabelText("Record payment for Car loan")).toBeNull(); });
});
