/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{ts,tsx,native.tsx}", "./index.{ts,tsx}", "./components/**/*.{ts,tsx}", "./screens/**/*.{ts,tsx}", "./features/**/*.{ts,tsx}", "./hooks/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        aqua950: "#013220",
        aqua700: "#0B8A55",
        aqua600: "#08B16A",
        aqua500: "#12D583",
        aqua400: "#41EDA4",
        aqua50: "#EFFEF7",
        canvas: "#E7E5DF",
        card: "#FCF8F0",
        surface: "#F8EFDC",
        line: "#EAEAE6",
        ink: "#1B1C1A",
        ink2: "#414942",
        muted: "#6B7A6F",
        errorSoft: "#FFF0F2",
        error: "#D9001F",
        warning: "#FB8E24",
        cta: "#013220",
        link: "#12D583",
        brand: "#12D583",
        heading: "#1B1C1A",
        text: "#414942",
        subtle: "#6B7A6F",
        accent: "#F8EFDC",
        success: "#12D583",
        white: "#FFFFFF",
        dangerSoft: "#FFF0F2",
        successSoft: "#EFFEF7",
      },
    },
  },
  plugins: [],
};
